from langgraph.graph import StateGraph,START,END
from utils.state import AgentState
from nodes.LoadDataset import Load_file
from nodes.DataProfiling import profile_dataframe
from nodes.PriorityGenerator_a import Priority_generator_a
from nodes.PriorityGenerator_b import Priority_generator_b
from nodes.PriorityGenerator_c import Priority_generator_c
from nodes.DataCleaningAgent import Clean_data,cleaning_tools_node,pop_executed_node_a,pop_executed_node_b,pop_executed_node_c
from nodes.EDA import perform_eda
from nodes.DataAnalysisAgent import Data_analysis,analysis_tools_node
from nodes.DataVisualizationAgent import Data_visualization,visualization_tools_node
from nodes.ChatAgent import chat_node,route_chat,rag_tool_node
from langgraph.prebuilt import tools_condition
from pathlib import Path, WindowsPath
import pandas as pd


graph=StateGraph(AgentState)
    
graph.add_node('LoadFile_node',Load_file)
graph.add_node('DataProfiling_node',profile_dataframe)
graph.add_node('PriorityGenerator1_node',Priority_generator_a)
graph.add_node('DataCleaning_node',Clean_data)
graph.add_node('cleaning_tools_node',cleaning_tools_node)
graph.add_node('pop_executed1_node',pop_executed_node_a)
graph.add_node('pop_executed2_node',pop_executed_node_b)
graph.add_node('pop_executed3_node',pop_executed_node_c)
graph.add_node('EDA_node',perform_eda)
graph.add_node('PriorityGenerator2_node',Priority_generator_b)
graph.add_node('DataAnalysis_node',Data_analysis)
graph.add_node('analysis_tools_node',analysis_tools_node)
graph.add_node('Chat_node',chat_node)
graph.add_node('RAG_tool_node',rag_tool_node)
graph.add_node('PriorityGenerator3_node',Priority_generator_c)
graph.add_node('DataVisualization_node',Data_visualization)
graph.add_node('visualization_tools_node',visualization_tools_node)


graph.add_edge(START,'LoadFile_node')
graph.add_edge('LoadFile_node','DataProfiling_node')
graph.add_edge('DataProfiling_node', 'PriorityGenerator1_node')
graph.add_edge('PriorityGenerator1_node','DataCleaning_node')
graph.add_conditional_edges(
    "DataCleaning_node",
    tools_condition,
    {
        "tools": "cleaning_tools_node",
        "__end__": "EDA_node"
    }
)
graph.add_edge('cleaning_tools_node','pop_executed1_node')
graph.add_edge('pop_executed1_node','DataCleaning_node')
graph.add_edge('EDA_node','PriorityGenerator2_node')
graph.add_edge('PriorityGenerator2_node','DataAnalysis_node')
graph.add_conditional_edges(
    "DataAnalysis_node",
    tools_condition,
    {
        "tools": "analysis_tools_node",
        "__end__": "Chat_node"
    }
)
graph.add_edge('analysis_tools_node','pop_executed2_node')
graph.add_edge('pop_executed2_node','DataAnalysis_node')
graph.add_conditional_edges(
    "chat_node",
    route_chat,
    {
        "chat_node": "chat_node",
        "PriorityGenerator3_node": "PriorityGenerator3_node"
    }
)

graph.add_conditional_edges(
    "chat_node",
    tools_condition,
    {
        "tools": "RAG_tool_node",
        "__end__": 'PriorityGenerator3_node'
    }
)
graph.add_edge('RAG_tool_node','Chat_node')
graph.add_edge('PriorityGenerator3_node','DataVisualization_node')
graph.add_conditional_edges(
    "DataVisualization_node",
    tools_condition,
    {
        "tools": "visualization_tools_node",
        "__end__": END
    }
)
graph.add_edge('visualization_tools_node','pop_executed3_node')
graph.add_edge('pop_executed3_node','DataVisualization_node')
# graph.add_edge('Query_node',END)



agent = graph.compile()

def run_agent(file_path: Path):
    try:
        initial_state = {"file_path": file_path, "df": None ,"report": {}, "cleaned_df": None, "eda_result": {}, "analysis_results": {}}
        
        final_state = agent.invoke(initial_state)
        
        return {
            'report': final_state['report'],
            'eda_result': final_state['eda_result'], 
            'analysis_results': final_state['analysis_results']
        }  # Safe access
        
    except KeyError:
        raise ValueError("DataFrame not generated by LoadFile_node (keyerror)")
    except Exception as e:
        raise RuntimeError(f"Graph execution failed: {str(e)}")
