from langgraph.graph import StateGraph,START,END
from langgraph.checkpoint.memory import MemorySaver
# from utils.dataframe_store import save_df
from langgraph.types import Command
from utils.state import AgentState
from nodes.LoadDataset import Load_file
from nodes.DataProfiling import profile_dataframe
from nodes.PriorityGenerator_a import Priority_generator_a
from nodes.PriorityGenerator_b import Priority_generator_b
from nodes.PriorityGenerator_c import Priority_generator_c
from nodes.DataCleaningAgent import Clean_data,cleaning_tools_node,pop_executed_node_a,pop_executed_node_b,pop_executed_node_c
from nodes.EDA import perform_eda
from nodes.DataAnalysisAgent import Data_analysis,analysis_tools_node
from nodes.SummaryGenerator import Generate_summary
from nodes.ChatAgent import chat_node,route_chat,rag_tool_node
from nodes.DataVisualizationAgent import Data_visualization,visualization_tools_node
from langgraph.prebuilt import tools_condition
from pathlib import Path, WindowsPath



graph=StateGraph(AgentState)
    
graph.add_node('LoadFile_node',Load_file)
graph.add_node('DataProfiling_node',profile_dataframe)
graph.add_node('PriorityGenerator1_node',Priority_generator_a)
graph.add_node('DataCleaning_node',Clean_data)
graph.add_node('cleaning_tools_node',cleaning_tools_node)
graph.add_node('pop_executed1_node',pop_executed_node_a)
graph.add_node('pop_executed2_node',pop_executed_node_b)
graph.add_node('pop_executed3_node',pop_executed_node_c)
graph.add_node('EDA_node',perform_eda)
graph.add_node('PriorityGenerator2_node',Priority_generator_b)
graph.add_node('DataAnalysis_node',Data_analysis)
graph.add_node('analysis_tools_node',analysis_tools_node)
graph.add_node('SummaryGenerator_node',Generate_summary)
graph.add_node('Chat_node',chat_node)
graph.add_node('RAG_tool_node',rag_tool_node)
graph.add_node('PriorityGenerator3_node',Priority_generator_c)
graph.add_node('DataVisualization_node',Data_visualization)
graph.add_node('visualization_tools_node',visualization_tools_node)


graph.add_edge(START,'LoadFile_node')
graph.add_edge('LoadFile_node','DataProfiling_node')
graph.add_edge('DataProfiling_node', 'PriorityGenerator1_node')
graph.add_edge('PriorityGenerator1_node','DataCleaning_node')
graph.add_conditional_edges(
    "DataCleaning_node",
    tools_condition,
    {
        "tools": "cleaning_tools_node",
        "__end__": "EDA_node"
    }
)
graph.add_edge('cleaning_tools_node','pop_executed1_node')
graph.add_edge('pop_executed1_node','DataCleaning_node')
graph.add_edge('EDA_node','PriorityGenerator2_node')
graph.add_edge('PriorityGenerator2_node','DataAnalysis_node')
graph.add_conditional_edges(
    "DataAnalysis_node",
    tools_condition,
    {
        "tools": "analysis_tools_node",
        "__end__": "SummaryGenerator_node"
    }
)
graph.add_edge('analysis_tools_node','pop_executed2_node')
graph.add_edge('pop_executed2_node','DataAnalysis_node')
graph.add_edge('SummaryGenerator_node','Chat_node')
graph.add_conditional_edges(
    "Chat_node",
    route_chat,
    {
        "Chat_node": "Chat_node",
        "tools": "RAG_tool_node",
        "PriorityGenerator3_node": "PriorityGenerator3_node"
    }
)

graph.add_edge('RAG_tool_node','Chat_node')
graph.add_edge('PriorityGenerator3_node','DataVisualization_node')
graph.add_conditional_edges(
    "DataVisualization_node",
    tools_condition,
    {
        "tools": "visualization_tools_node",
        "__end__": END
    }
)
graph.add_edge('visualization_tools_node','pop_executed3_node')
graph.add_edge('pop_executed3_node','DataVisualization_node')




# agent = graph.compile()

# def run_agent(file_path: Path):
#     try:
#         initial_state = {"file_path": file_path, "df": None ,"report": {}, "cleaned_df": None, "eda_result": {}, "analysis_results": {}}
        
#         final_state = agent.invoke(initial_state)
        
#         return {
#             'report': final_state['report'],
#             'eda_result': final_state['eda_result'], 
#             'analysis_results': final_state['analysis_results']
#         }  # Safe access
        
#     except KeyError:
#         raise ValueError("DataFrame not generated by LoadFile_node (keyerror)")
#     except Exception as e:
#         raise RuntimeError(f"Graph execution failed: {str(e)}")



 
checkpointer = MemorySaver()
agent = graph.compile(checkpointer=checkpointer)
 
 
# ── Config helper ────────────────────────────────────────────────────────────
 
def _config(thread_id: str) -> dict:
    return {"configurable": {"thread_id": thread_id}}
 
 
# ── Public API ───────────────────────────────────────────────────────────────
 
def start_graph(file_path: Path, thread_id: str) -> None:
    """
    Kick off graph execution for a new session.
    Blocks until the graph either hits interrupt() at Chat_node
    or reaches END (if something fails and chat is skipped).
 
    Raises RuntimeError on graph execution failure.
    """
    initial_state = {
        "file_path":            str(file_path),   # serialize as string
        "df_key":               "",               # populated by LoadFile node
        "clean_df_key":         "",
        "report":               {},
        "cleaning_summary":     {},
        "tool_priority_list_1": [],
        "eda_result":           {},
        "eda_summary":          {},
        "tool_priority_list_2": [],
        "analysis_results":     {},
        "tool_priority_list_3": [],
        "chat_history":         [],
        "chat_active":          True,
        "messages":             [],
    }
    try:
        agent.invoke(initial_state, config=_config(thread_id))
    except Exception as e:
        raise RuntimeError(f"Graph execution failed: {e}") from e
 
 
def get_graph_status(thread_id: str) -> dict:
    try:
        snapshot = agent.get_state(config=_config(thread_id))
    except Exception:
        return {"stage": "unknown"}

    if snapshot is None:
        return {"stage": "unknown"}

    next_nodes = snapshot.next
    tasks = snapshot.tasks

    # ── Interrupted tasks = graph is paused at interrupt() ───────────────────
    # MUST be checked before the general tasks check, because interrupted
    # tasks are still present in snapshot.tasks but the graph is NOT running.
    for task in tasks:
        if hasattr(task, "interrupts") and task.interrupts:
            latest_ai_message = _extract_latest_ai_message(snapshot.values)
            return {"stage": "chatting", "latest_message": latest_ai_message}

    # ── Non-interrupted pending tasks → still processing ─────────────────────
    if tasks:
        return {"stage": "processing"}

    # ── No tasks, no next nodes → reached END ────────────────────────────────
    if not next_nodes:
        return {"stage": "done"}

    # ── Paused at Chat_node (fallback for edge cases) ─────────────────────────
    if "Chat_node" in next_nodes:
        latest_ai_message = _extract_latest_ai_message(snapshot.values)
        return {"stage": "chatting", "latest_message": latest_ai_message}

    # ── Visualization nodes queued ────────────────────────────────────────────
    if any(n in next_nodes for n in (
        "PriorityGenerator3_node", "DataVisualization_node", "visualization_tools_node"
    )):
        return {"stage": "visualizing"}

    return {"stage": "processing"}
 
 
def send_chat_message(thread_id: str, user_message: str) -> dict:
    """
    Resume the graph from interrupt() with the user's message.
    Blocks until the graph hits interrupt() again or reaches END.
 
    Returns:
      {
        "stage":          "chatting" | "done" | "visualizing",
        "latest_message": "<AI reply text or empty string>"
      }
    """
    try:
        agent.invoke(
            Command(resume=user_message),
            config=_config(thread_id),
        )
    except Exception as e:
        raise RuntimeError(f"Chat resume failed: {e}") from e
 
    return get_graph_status(thread_id)
 
 
def get_visualization_paths(thread_id: str) -> list[str]:
    """
    Returns the list of image file paths written to ./visualizations/
    by reading them from the final graph state.
 
    Falls back to scanning the directory if the state does not carry paths.
    """
    try:
        snapshot = agent.get_state(config=_config(thread_id))
        state_values = snapshot.values if snapshot else {}
        # If your DataVisualizationAgent stores paths in state, adapt the key below.
        viz_paths = state_values.get("visualization_paths", [])
        if viz_paths:
            return [str(p) for p in viz_paths]
    except Exception:
        pass
 
    # Fallback: scan the fixed output folder
    from pathlib import Path
    viz_dir = Path("./visualizations")
    if viz_dir.exists():
        return sorted(str(p) for p in viz_dir.glob("*.png")) + \
               sorted(str(p) for p in viz_dir.glob("*.jpg"))
    return []
 
 
# ── Internal helpers ─────────────────────────────────────────────────────────
 
def _extract_latest_ai_message(state_values: dict) -> str:
    from langchain_core.messages import AIMessage
    messages = state_values.get("messages", [])
    # Walk backwards, skip ToolMessages and HumanMessages
    for msg in reversed(messages):
        if isinstance(msg, AIMessage):
            # Skip AIMessages that are just tool calls with no text content
            if isinstance(msg.content, str) and msg.content.strip():
                return msg.content
            # Handle list content (some models return [{type: text, text: ...}])
            if isinstance(msg.content, list):
                for block in msg.content:
                    if isinstance(block, dict) and block.get("type") == "text":
                        text = block.get("text", "").strip()
                        if text:
                            return text
    return ""
 