from langgraph.graph import StateGraph,START,END
from utils.state import AgentState
from nodes.LoadDataset import Load_file
from nodes.DataProfiling import profile_dataframe
from nodes.DataCleaningAgent import Clean_data
from nodes.EDA import perform_eda
from nodes.DataAnalysisAgent import Data_analysis
from nodes.DataVisualizationAgent import Data_visualization
from nodes.QueryAgent import User_query
from pathlib import Path
import pandas as pd


graph=StateGraph(AgentState)
    
graph.add_node('LoadFile_node',Load_file)
graph.add_node('DataProfiling_node',profile_dataframe)
graph.add_node('DataCleaning_node',Clean_data)
graph.add_node('EDA_node',perform_eda)
graph.add_node('DataAnalysis_node',Data_analysis)
graph.add_node('DataVisualization_node',Data_visualization)
graph.add_node('Query_node',User_query)


graph.add_edge(START,'LoadFile_node')
graph.add_edge('LoadFile_node','DataProfiling_node')
graph.add_edge('DataProfiling_node','DataCleaning_node')
graph.add_edge('DataCleaning_node','EDA_node')
graph.add_edge('EDA_node','DataAnalysis_node')
graph.add_edge('DataAnalysis_node','DataVisualization_node')
graph.add_edge('DataVisualization_node','Query_node')
graph.add_edge('Query_node',END)


agent = graph.compile()

def run_agent(file_path: Path):
    try:
        initial_state = {"file_path": file_path, "df": None ,"report": {}, "cleaned_df": None, "eda_result": {}}
        final_state = agent.invoke(initial_state)
        
        return final_state['report']  # Safe access
    except KeyError:
        raise ValueError("DataFrame not generated by LoadFile_node (keyerror)")
    except Exception as e:
        raise RuntimeError(f"Graph execution failed: {str(e)}")
